spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            apigateway:
              - uri: http://apigateway:9000
            techinterview:
              - uri: http://techinterview:9040