server:
  port: 9100
spring:
  application:
    name: admin-service
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:h2:mem:dummy
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# 로깅 설정
logging:
  level:
    root: INFO
    de.codecentric.boot.admin: DEBUG
    org.springframework.web: INFO

# Eureka 설정 (만약 사용 중이라면)
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false