spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  cloud:
    discovery:
      client:
        simple:
          instances:
            apigateway:
              - uri: http://apigateway:9000
            auth:
                - uri: http://auth:9010
            member:
                - uri: http://member:9020
            space:
                - uri: http://space:9030
            techinterview:
              - uri: http://techinterview:9040
            resume:
              - uri: http://resume:9060
  boot:
    admin:
      discovery:
        enabled: true
      monitor:
        status-lifetime: 100000
      ui:
        external-views:
          - label: "Prometheus"
            url: "http://210.113.34.187:9200"
            order: 2000
          - label: "Grafana"
            url: "http://210.113.34.187:3000"
            order: 2001
          - label: "JPA 쿼리 모니터링"
            url: "/custom-dashboard"
            order: 1000
          - label: "JPA 쿼리 모니터링"
            url: "http://210.113.34.187:9300"
            order: 2002