spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            apigateway:
              - uri: http://172.30.1.23:9000
            techinterview:
              - uri: http://172.30.1.23:9040
  boot:
    admin:
      client:
        instance:
          service-url: http://172.30.1.23:${server.port}
          management-url: http://172.30.1.23:${server.port}/actuator
          health-url: http://172.30.1.23:${server.port}/actuator/health