global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['apigateway:9000']  # 컨테이너 별칭 사용

  - job_name: 'techinterview'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['techinterview:9040']  # 컨테이너 별칭 사용

  - job_name: 'admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin:9100']  # 컨테이너 별칭 사용